# Generated by Django 5.2.7 on 2025-12-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='eventcomment',
            old_name='comment',
            new_name='message',
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='is_admin_reply',
            field=models.BooleanField(default=False),
        ),
    ]
